package com.example.example.spring.mybatis.model;

import java.util.Date;

public class TodoList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.task_id
     *
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.task_name
     *
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.task_detail
     *
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    private String taskDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.status
     *
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.limit_date
     *
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    private Date limitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.create_date
     *
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.lastmodify_date
     *
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    private Date lastmodifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.task_id
     *
     * @return the value of todo_list.task_id
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.task_id
     *
     * @param taskId the value for todo_list.task_id
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.task_name
     *
     * @return the value of todo_list.task_name
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.task_name
     *
     * @param taskName the value for todo_list.task_name
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.task_detail
     *
     * @return the value of todo_list.task_detail
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public String getTaskDetail() {
        return taskDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.task_detail
     *
     * @param taskDetail the value for todo_list.task_detail
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public void setTaskDetail(String taskDetail) {
        this.taskDetail = taskDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.status
     *
     * @return the value of todo_list.status
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.status
     *
     * @param status the value for todo_list.status
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.limit_date
     *
     * @return the value of todo_list.limit_date
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public Date getLimitDate() {
        return limitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.limit_date
     *
     * @param limitDate the value for todo_list.limit_date
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public void setLimitDate(Date limitDate) {
        this.limitDate = limitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.create_date
     *
     * @return the value of todo_list.create_date
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.create_date
     *
     * @param createDate the value for todo_list.create_date
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.lastmodify_date
     *
     * @return the value of todo_list.lastmodify_date
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public Date getLastmodifyDate() {
        return lastmodifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.lastmodify_date
     *
     * @param lastmodifyDate the value for todo_list.lastmodify_date
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    public void setLastmodifyDate(Date lastmodifyDate) {
        this.lastmodifyDate = lastmodifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TodoList other = (TodoList) that;
        return (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
                && (this.getTaskName() == null ? other.getTaskName() == null : this.getTaskName().equals(other.getTaskName()))
                && (this.getTaskDetail() == null ? other.getTaskDetail() == null : this.getTaskDetail().equals(other.getTaskDetail()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getLimitDate() == null ? other.getLimitDate() == null : this.getLimitDate().equals(other.getLimitDate()))
                && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
                && (this.getLastmodifyDate() == null ? other.getLastmodifyDate() == null : this.getLastmodifyDate().equals(other.getLastmodifyDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated Wed Jul 19 17:14:31 JST 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getTaskName() == null) ? 0 : getTaskName().hashCode());
        result = prime * result + ((getTaskDetail() == null) ? 0 : getTaskDetail().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLimitDate() == null) ? 0 : getLimitDate().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getLastmodifyDate() == null) ? 0 : getLastmodifyDate().hashCode());
        return result;
    }
}